name: run dbt Cloud job on push

on:
  push:
    branches:
      - main

  run_dbt_cloud_job:
    name: Run dbt Cloud Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dbt
        run: |
          pip install dbt
          dbt deps

      - name: Run dbt
        run: dbt run
