version: 2

sources:
  - name: paris # this is the source_name
    database: dbt_demo_dev
    schema: paris_raw

    tables:
      - name: calendar # this is the table_name
      - name: listings
      - name: reviews